In [1]:
import tensorflow as tf

> 张量 计算图 会话 参数 前向传播 反向传播 八股 代码
    
- 张量(tensor):  多维数组(列表) 表示数据 阶：张量的维数

In [2]:
tf.__version__

'1.11.0'

In [3]:
tf.__path__

['/usr/local/lib/python3.5/dist-packages/tensorflow',
 '/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/api']

加法

In [4]:
a = tf.constant([1.0, 2.0])
b = tf.constant([3.0, 4.0])
result = a+b
print(result)

Tensor("add:0", shape=(2,), dtype=float32)


计算图

In [8]:
a = tf.constant([[1.0, 2.0]])
b = tf.constant([[3.0], [4.0]])
y = tf.matmul(a,b)
print(y)

Tensor("MatMul_3:0", shape=(1, 1), dtype=float32)


会话

In [9]:
with tf.Session() as s:
    print(s.run(y))

[[11.]]


参数

In [12]:
w=tf.Variable(tf.random_normal([2,3], stddev=2, mean=0, seed=1))
print(w)

<tf.Variable 'Variable_1:0' shape=(2, 3) dtype=float32_ref>


In [25]:
# import and generate dataset
import tensorflow as tf
import numpy as np
BATCH_SIZE = 8
seed=23423

rng = np.random.RandomState(seed)
X=rng.rand(32,2)
Y=[[int(x0 + x1 < 1)] for (x0, x1) in X]
print(X, Y)

[[0.89100872 0.04547942]
 [0.58995479 0.74325738]
 [0.54527523 0.00603509]
 [0.46616489 0.56627563]
 [0.0602572  0.32196404]
 [0.04619735 0.30706376]
 [0.93903912 0.88762515]
 [0.54431337 0.03241746]
 [0.7645021  0.9565903 ]
 [0.68507079 0.12937562]
 [0.41134516 0.26407252]
 [0.16795192 0.24138889]
 [0.08902241 0.71555968]
 [0.69160873 0.95994049]
 [0.49257184 0.16839914]
 [0.18335744 0.15183223]
 [0.27884175 0.92810696]
 [0.17897793 0.31386106]
 [0.08601798 0.20717024]
 [0.04684421 0.72187585]
 [0.29003739 0.67867766]
 [0.61511528 0.51282158]
 [0.58501644 0.36517502]
 [0.02384557 0.10471851]
 [0.6252292  0.49268034]
 [0.7107483  0.87383086]
 [0.97148624 0.41108   ]
 [0.69948235 0.4663255 ]
 [0.78100109 0.71221726]
 [0.71327586 0.88199801]
 [0.48002231 0.39066195]
 [0.9782135  0.15356219]] [[1], [0], [1], [0], [1], [1], [0], [1], [0], [1], [1], [1], [1], [0], [1], [1], [0], [1], [1], [1], [1], [0], [1], [1], [0], [0], [0], [0], [0], [0], [1], [0]]


In [37]:
# defind input, val and output
x=tf.placeholder(tf.float32, shape=(None,2))
y_=tf.placeholder(tf.float32, shape=(None,1))
print(x, y)

w1=tf.Variable(tf.random_normal([2,3],stddev=1, seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1, seed=1))

a=tf.matmul(x, w1)
y=tf.matmul(a, w2)

Tensor("Placeholder_10:0", shape=(?, 2), dtype=float32) Tensor("MatMul_11:0", shape=(?, 1), dtype=float32)


In [33]:
# bp
loss=tf.reduce_mean(tf.square(y-y_))
train_step=tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [36]:
# session
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print("w1:", sess.run(w1))
    print("w2:", sess.run(w2))
    
    steps = 3000
    for i in range(steps):
        start = (i*BATCH_SIZE)%32
        end = start + BATCH_SIZE
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
#         if i%500==0:
#             total_loss=sess.run(loss, feed_dict_dict={x:X,y_:Y})
#             print("After %d traing steps, loss is %g" %(i,total_loss))
    print("w1(after):", sess.run(w1))
    print("w2(after):", sess.run(w2))

w1: [[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
w2: [[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
w1(after): [[-0.695194    0.831272    0.09577356]
 [-2.3404582  -0.13303831  0.5870709 ]]
w2(after): [[-0.03137202]
 [ 0.83532155]
 [-0.06769659]]


In [23]:
print(train_step)

name: "GradientDescent"
op: "NoOp"
input: "^GradientDescent/update_Variable_6/ApplyGradientDescent"
input: "^GradientDescent/update_Variable_7/ApplyGradientDescent"



In [30]:
X[start:end]

array([[0.89100872, 0.04547942],
       [0.58995479, 0.74325738],
       [0.54527523, 0.00603509],
       [0.46616489, 0.56627563],
       [0.0602572 , 0.32196404],
       [0.04619735, 0.30706376],
       [0.93903912, 0.88762515],
       [0.54431337, 0.03241746]])

In [31]:
Y[start:end]

[[1], [0], [1], [0], [1], [1], [0], [1]]

In [43]:
np.random.uniform(0,1)

0.39906976443827624

In [71]:
n=10
cards = [i+1 for i in range(n)]
cards
for k in range(n-1,0,-1):
    u=np.random.uniform(0,1)
    i=int(k*u)+1
    print(u, i, k)
    cards[i],cards[k]=cards[k], cards[i]
cards

0.21537906539337992 2 9
0.10556796328569229 1 8
0.1518224401624707 2 7
0.4924483389712375 3 6
0.23508419049917206 2 5
0.05109264723052187 1 4
0.1016554701139758 1 3
0.3695202964800658 1 2
0.8463651144512215 1 1


[1, 6, 7, 5, 9, 8, 4, 10, 2, 3]

In [84]:
rdm = np.random.RandomState(23455)
rdm.rand(32,2)

array([[0.83494319, 0.11482951],
       [0.66899751, 0.46594987],
       [0.60181666, 0.58838408],
       [0.31836656, 0.20502072],
       [0.87043944, 0.02679395],
       [0.41539811, 0.43938369],
       [0.68635684, 0.24833404],
       [0.97315228, 0.68541849],
       [0.03081617, 0.89479913],
       [0.24665715, 0.28584862],
       [0.31375667, 0.47718349],
       [0.56689254, 0.77079148],
       [0.7321604 , 0.35828963],
       [0.15724842, 0.94294584],
       [0.34933722, 0.84634483],
       [0.50304053, 0.81299619],
       [0.23869886, 0.9895604 ],
       [0.4636501 , 0.32531094],
       [0.36510487, 0.97365522],
       [0.73350238, 0.83833013],
       [0.61810158, 0.12580353],
       [0.59274817, 0.18779828],
       [0.87150299, 0.34679501],
       [0.25883219, 0.50002932],
       [0.75690948, 0.83429824],
       [0.29316649, 0.05646578],
       [0.10409134, 0.88235166],
       [0.06727785, 0.57784761],
       [0.38492705, 0.48384792],
       [0.69234428, 0.19687348],
       [0.

In [107]:
rdm.rand()

0.43779119014338297

In [102]:
np.random.rand()

0.26551572007999347