In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)

total = a + b

In [3]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2

In [4]:
sess = tf.Session()
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.75339234 0.9596709  0.7780293 ]
[0.05856049 0.31746006 0.83191156]
(array([1.6179622, 1.2520864, 1.6090746], dtype=float32), array([2.6179624, 2.2520864, 2.6090746], dtype=float32))


In [20]:
writer = tf.summary.FileWriter('graph')
writer.add_graph(tf.get_default_graph())

In [6]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [7]:
sess.run(z, feed_dict={x: 3, y: 4.5}), sess.run(z, feed_dict={x:[1,3], y:[2,4]})

(7.5, array([3., 7.], dtype=float32))

In [8]:
my_data = [
    [0,1,],
    [2,3,],
    [4,5,],
    [6,7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [9]:
while True:
    try:
        print(sess.run(next_item))
    except tf.errors.OutOfRangeError:
        break

[0 1]
[2 3]
[4 5]
[6 7]


In [10]:
r = tf.random_normal([10, 3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)

In [11]:
while True:
    try:
        print(sess.run(next_row))
    except tf.errors.OutOfRangeError:
        break

[2.023197   0.38006184 1.7302902 ]
[-1.3204829   0.4411538  -0.08117437]
[ 0.29025954 -0.8107155   0.39350334]
[-1.6850444   0.6940427   0.12030738]
[-0.94130486 -0.91112286 -1.7334143 ]
[ 1.6586254   0.13314848 -0.8118336 ]
[-0.38904953 -0.4303455  -0.6388648 ]
[ 0.33801717  0.7358265  -0.03873709]
[1.0168004 1.4855748 0.8863632]
[-0.00194984  0.17093     0.21448621]


In [5]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

init = tf.global_variables_initializer()
sess.run(init)

In [6]:
sess.run(y, {x: [[1,2,3], [4,5,6]]})

array([[-0.10916471],
       [ 0.08358634]], dtype=float32)

In [8]:
features = {
    'sales': [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']
}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
    'department', ['sports', 'gardening'])

department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [19]:
with tf.variable_scope('v_scope'):
    with tf.name_scope('n_scope'):
        x = tf.Variable([1], name='x')
        y = tf.get_variable('x', shape=[1], dtype=tf.int32)
        z = x + y
#         k = x + y
x.name, y.name, z.name 

('v_scope/n_scope/x:0', 'v_scope/x:0', 'v_scope/n_scope/add:0')