<a href="https://colab.research.google.com/github/idleyui/python-notebook/blob/master/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import random

In [0]:
t = torch.tensor(range(4)).reshape(4,1)
t

tensor([[0],
        [1],
        [2],
        [3]])

In [0]:
t.expand(-1, 4)

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [0]:
t# expand only works along *singleton* dimensions of the input tensor, this won't work
# https://stackoverflow.com/questions/53975352/using-expand-dims-in-pytorch
t.expand(8, -1)

RuntimeError: ignored

In [0]:
l = list(range(12))
random.shuffle(l)
l

[5, 0, 10, 8, 3, 7, 6, 1, 2, 11, 4, 9]

In [0]:
random_t = torch.tensor(l).reshape(3,4)
random_t

tensor([[ 5,  0, 10,  8],
        [ 3,  7,  6,  1],
        [ 2, 11,  4,  9]])

In [0]:
random_t.topk(2)

torch.return_types.topk(values=tensor([[10,  8],
        [ 7,  6],
        [11,  9]]), indices=tensor([[2, 3],
        [1, 2],
        [1, 3]]))

In [0]:
random_t

tensor([[ 5,  0, 10,  8],
        [ 3,  7,  6,  1],
        [ 2, 11,  4,  9]])

In [0]:
random_t.new_full((*random_t.size(), 2), -1)

tensor([[[-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1]],

        [[-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1]],

        [[-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1]]])

In [0]:
predict = torch.Tensor(list(range(6))).reshape(2,3)
attn = torch.Tensor(list(range(24))).reshape(2,3,4)
predict

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [0]:
attn

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [0]:
index = torch.LongTensor([[2,1,0],[0,1,2]])
index

tensor([[2, 1, 0],
        [0, 1, 2]])

In [0]:
attn_index = index.unsqueeze(-1).expand_as(b)
attn_index

tensor([[[2, 2, 2, 2],
         [1, 1, 1, 1],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [0]:
torch.gather(attn, dim=1, index=attn_index)

tensor([[[ 8.,  9., 10., 11.],
         [ 4.,  5.,  6.,  7.],
         [ 0.,  1.,  2.,  3.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [0]:
torch.gather(predict, dim=1, index=index)

tensor([[2., 1., 0.],
        [3., 4., 5.]])